#!/usr/bin/env node
/**
 * Copy Cesium's runtime assets into static/cesiumStatic.
 *
 * Cesium loads widget images, web workers and third-party libs at RUNTIME from
 * `CESIUM_BASE_URL`, not through the bundler. Without them the viewer 404s on
 * every asset it asks for — measured at 10 failed requests on ?engine=cesium —
 * and none of that is visible to `bun run build`, which is why this has to be
 * an explicit step rather than something the bundler is trusted to notice.
 *
 * NOT committed: ~22 MB of vendor output belongs in node_modules, not in git.
 * Regenerated by `bun run sync:cesium`, which `build` runs first.
 */
import { cpSync, existsSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'node_modules/cesium/Build/Cesium');
const dest = join(root, 'static/cesiumStatic');

if (!existsSync(src)) {
	// Not an error: cesium is only needed for the experimental ?engine=cesium
	// path, and the kiosk default is MapLibre.
	console.warn('[sync-cesium] node_modules/cesium not found — skipping');
	process.exit(0);
}

rmSync(dest, { recursive: true, force: true });
mkdirSync(dest, { recursive: true });
for (const part of ['Assets', 'Widgets', 'Workers', 'ThirdParty']) {
	const from = join(src, part);
	if (existsSync(from)) cpSync(from, join(dest, part), { recursive: true });
}
console.log(`[sync-cesium] copied Cesium runtime assets -> static/cesiumStatic`);
